### ISSUE TITLE
error when generating backdoor.

### ISSUE THREAD

**Issue by b4sh1t1** [7h3w4lk3r/pyback#5]
Hi, 

Running default setting and when it's comes to generate backdoor it's stop with this error;

FO     Start obfuscating the scripts...
INFO     	backdoor.py -> dist/obf/backdoor.py
ERROR    invalid syntax (<frozen backdoor>, line 51)
INFO     ==================== End command ====================

ERROR    Run command failed
Traceback (most recent call last):
  File "config.py", line 148, in <module>
    generator()
  File "config.py", line 126, in generator
    obfuscate()
  File "config.py", line 145, in obfuscate
    print(subprocess.check_output('pyarmor pack -e "--onefile --noconsole" backdoor.py',shell=True))
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pyarmor pack -e "--onefile --noconsole" backdoor.py' returned non-zero exit status 1

any idea ?

**Comment by 7h3w4lk3r** [comment]
from the error output im guessing that the host OS is linux. if you generated a backdoor before and its still running on the system the script will fail to overwrite it with the new backdoor. so check if there is a backdoor running in the system and stop it before running the script again. ill do better error handling for this script when i get the time.

**Comment by b4sh1t1** [comment]
it's parrot os, and new without backdoor installed; maybe the reaon for the ip which make it froze to generate ?

**Comment by 7h3w4lk3r** [comment]
> it's parrot os, and new without backdoor installed; maybe the reaon for the ip which make it froze to generate ?

be more specific, what are the parameters you entered in the configuration? check you input and try to compile the backdoor manually with and without pyarmor to see if the problem is related to the script or your system.

**Comment by 7h3w4lk3r** [comment]
i'm closing this due to inactivity.
